# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
